### ISSUE TITLE
Column background does not repeat when grid is resized.

### ISSUE THREAD

**Issue by tonosama-atlacatl** [bwu-dart/bwu_datagrid#128]
The background image for "bwu-datagrid-headers" does not tile when resizing the datagrid. Part of the problem is that the computed "width" pixel value for bwu-datagrid-headers never changes.
**backround in question:**
``` CSS
bwu-datagrid-headers.bwu-datagrid-headers-0 {
    background: url('http://localhost:63342/XXXXXXXXXX/web/
packages/bwu_datagrid/asset/images/header-columns-bg.gif') repeat-x center bottom;
    border-bottom: 1px solid silver;
}
```
**Example of afflicted control:**
``` HTML
<!-- Notice how the width is set to 1784px, but if you expand the window to something higher, this 
       problem becomes visible -->
<bwu-datagrid-headers id="bwuDatagridHeaders" class="bwu-datagrid-header-columns style-scope
bwu-datagrid x-scope bwu-datagrid-headers-0" unselectable="on" style="left: -1000px; width: 1784px;
-webkit-user-select: none;"><bwu-datagrid-header-column class="ui-state-default bwu-datagrid-
header-column x-scope bwu-datagrid-header-column-0" id="title" title="" ismovable="true"
 style="width: 71px;">
```

**How does it look:**
![screen shot 2016-03-21 at 4 27 19 pm](https://cloud.githubusercontent.com/assets/10780925/13937556/ea39e2a4-ef82-11e5-8bf9-70201f6012a0.png)

**Setup:**
bwu_datagrid: 0.1.0-dev.0
sdk: 1.15
polymer: ^1.0.0-rc.5
