### ISSUE TITLE
Get rid of path dependencies in `example_` 

### ISSUE THREAD

**Issue by zoechi** [bwu-dart/bwu_datagrid#150]
```yaml
dev_dependencies:
  bwu_webdriver:  
    path: ../../bwu_webdriver
  bwu_docker:
    path: ../../bwu_docker
```
