### ISSUE TITLE
FOUC prevention seems not to work on Chrome 34

### ISSUE THREAD

**Issue by zoechi** [bwu-dart/bwu_datagrid#60]
@JamesHurford reported at https://plus.google.com/u/0/+G%C3%BCnterZ%C3%B6chbauer/posts/hWLqrPSUCUC
that the Grid in the 04_model example is not show until he removes 

``` CSS
app-element * :unresolved, app-element * [unresolved] {
 opacity: 0;
}
```

from the pages CSS
